name: Playground Build And Deploy

#on:
#  workflow_call:
#    inputs:
#      ecr-repository:
#        required: true
#        type: string
#      dockerfile:
#        required: true
#        type: string

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      choice:
        type: choice
        description: Choice Build Module
        options:
          - github-actions-lab
          - sample-module

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          role-session-name: playground-build
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build and Test with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker build env
        id: build-env
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "::set-output name=image_tag_version::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Build, tag, and push image to Amazon ECR
        id: build-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /${{ inputs.choice }}/Dockerfile
          push: true
          tags: ${{ steps.build-env.outputs.image_tag_version }}
