name: 'Deploy Test'

on:
  workflow_dispatch:

jobs:
  playground-build-and-push:
    uses: seungjjun/github-actions-lab/.github/workflows/build-and-push.yml@main
    with:
      ecr-repository: playground-dev
      dockerfile: Dockerfile
