name: 'Deploy Test'

on:
  workflow_dispatch:

jobs:
  build-test:
    uses: seungjjun/github-actions-lab/.github/workflows/build_pr.yml@main

    playground-build-and-push:
      needs: [ build-test ]
      uses: seungjjun/github-actions-lab/.github/workflows/deploy.yml@main
