name: 'Deploy Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Choice Module Environment
        options:
          - dev
          - prod
      module:
        required: true
        type: choice
        description: Choice Build Module
        options:
          - github-actions-lab
          - sample-module

jobs:
  github-actions-lab-build-and-push:
    if: ${{ github.event.inputs.module == 'github-actions-lab' }}
    uses: seungjjun/github-actions-lab/.github/workflows/build-and-push.yml@main
    with:
      ecr-repository: playground-dev
      dockerfile: github-actions-lab/Dockerfile
      choice: github-actions-lab

  sample-module-build-and-push:
    if: ${{ github.event.inputs.choice == 'sample-module' }}
    uses: seungjjun/github-actions-lab/.github/workflows/build-and-push.yml@main
    with:
      ecr-repository: playground-dev
      dockerfile: sample-module/Dockerfile
      choice: sample-module
