name: 'Deploy Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Choice Module Environment
        options:
          - dev
          - prod
      module:
        required: true
        type: choice
        description: Choice Build Module
        options:
          - github-actions-lab
          - sample-module

jobs:
  build-and-push:
    strategy:
      matrix:
        environment: [dev, prod]
        module: [github-actions-lab, sample-module]
    if: ${{ github.event.inputs.environment == matrix.environment && github.event.inputs.module == matrix.module }}
    uses: seungjjun/github-actions-lab/.github/workflows/build-and-push.yml@main
    with:
      ecr-repository: playground-${{ matrix.environment }}
      dockerfile: ${{ matrix.module }}/Dockerfile
      choice: ${{ matrix.module }}
